import React from 'react';

export const metadata = {
	description: 'Generated by create next app',
};

export default function Layout({children}) {
	return (
		<>
			<h1 className='text-5xl text-right w-full text-orange-900 bg-emerald-500'>HAHAHA</h1>
			{children}
			<nav className='flex flex-row bg-neutral-700 w-full max-w-sm'>
				<i className='bx bx-home text-red-800 basis-1/4 mr-32'></i>
				<i className='bx bx-search-alt-2 basis-1/4' ></i>
				<i className='bx bxs-bell basis-1/4' ></i>
				<i className='bx bx-envelope basis-1/4' ></i>
			</nav>
		</>
	);
}