import React from 'react';

export const metadata = {
	description: 'Generated by create next app',
};

export default function Layout({children}) {
	return (
		<>
			<h1>HAHAHA</h1>
			{children}
			<i className='bx bx-home text-red-800'></i>
			<i className='bx bx-search-alt-2' ></i>
			<i className='bx bxs-bell' ></i>
			<i className='bx bx-envelope' ></i>
			<i className='bx bx-envelope text-red-800' ></i>
		</>
	);
}