import React from 'react';
import Navbar from '@/components/navbar';
import Circle from '@/components/circle';
import Header from '@/components/header';
import { useRouter } from 'next/router';

export const metadata = {
	description: 'Generated by create next app',
};

export default function Layout({children}) {
	let router = useRouter();
	console.log(router);
	const isTweet = router.pathname === '/tweet';
	// if (isTweet) {
		
	// }
	return (
		<main className='w-full'>
			<div className='w-3/6 mx-auto'>
				{!isTweet && (<>
					<Header/>
					<div className='pt-16 bg-white '>
						{children}
					</div>
				</>)}
				<div className='p-5 bg-white h-screen'>
					{children}
				</div>
				
				{!isTweet && (
					<>
						<Circle/>
						<Navbar/>
					</>)}
			</div>
		</main>
	);
}